/**
 * Guards the committed fixture against drift.
 *
 * fixtures/demo-draft.json is generated by `pnpm fixture`, but it is the
 * committed file that every later milestone renders from. If the schema or a
 * compute rule changes and the fixture is not regenerated, these tests fail
 * rather than letting the renderers be built against stale numbers.
 */

import { describe, expect, it } from "vitest";

import demo from "../../fixtures/demo-draft.json";
import { recomputeDraft } from "@/lib/compute";
import { DraftSchema, summariseZodError } from "@/lib/schema";

describe("fixtures/demo-draft.json", () => {
  const parsed = DraftSchema.safeParse(demo);

  it("satisfies the schema", () => {
    expect(parsed.success ? null : summariseZodError(parsed.error, 20)).toBeNull();
  });

  it("has the shape the milestones assume", () => {
    expect(parsed.success).toBe(true);
    if (!parsed.success) return;

    const draft = parsed.data;
    expect(draft.participants).toHaveLength(8);
    expect(draft.sessions).toHaveLength(5);
    expect(draft.gradeColumns).toHaveLength(3);
    expect(draft.survey.questions).toHaveLength(6);
  });

  it("is already recomputed — the committed numbers are the real ones", () => {
    expect(parsed.success).toBe(true);
    if (!parsed.success) return;

    // If this fails, run `pnpm fixture`.
    expect(recomputeDraft(parsed.data)).toEqual(parsed.data);
  });

  it("carries the RTL edge cases the renderers need", () => {
    expect(parsed.success).toBe(true);
    if (!parsed.success) return;

    const draft = parsed.data;

    // A Latin-script name inside an otherwise Arabic column: the row that
    // catches bidi reversal in the Word and Excel tables.
    const latin = draft.participants.find((p) => /^[\x20-\x7E]+$/.test(p.nameAr));
    expect(latin, "expected one participant with a Latin-script name").toBeDefined();

    // A long digit string inside Arabic prose: the other bidi trap.
    const narrative = Object.values(draft.narrative).join(" ");
    expect(narrative).toMatch(/\d{8,}/);

    // Arabic must be present throughout, not just in one field.
    for (const [field, text] of Object.entries(draft.narrative)) {
      expect(text, `narrative.${field} should be non-empty Arabic`).toMatch(/[؀-ۿ]/);
    }
  });

  it("exercises the outcome rules rather than a single happy path", () => {
    expect(parsed.success).toBe(true);
    if (!parsed.success) return;

    const draft = parsed.data;
    const by = (id: string) => draft.participants.find((p) => p.id === id);

    // Late at every session still counts as full attendance.
    expect(by("p4")?.computed.lateCount).toBe(5);
    expect(by("p4")?.computed.attendanceRate).toBe(100);

    // An excused session leaves the denominator.
    expect(by("p5")?.computed.excusedCount).toBe(1);
    expect(by("p5")?.computed.attendanceRate).toBe(100);

    // One participant fails on attendance, another on score.
    expect(by("p6")?.computed.computedOutcome).toBe("failed");
    expect(by("p6")?.computed.totalScore).toBeGreaterThanOrEqual(draft.course.passing.minScore);
    expect(by("p7")?.computed.attendanceRate).toBe(100);
    expect(by("p7")?.computed.computedOutcome).toBe("failed");

    // And one carries a human override, with the computed value preserved.
    expect(by("p8")?.computed.computedOutcome).toBe("failed");
    expect(by("p8")?.computed.outcome).toBe("passed");
    expect(by("p8")?.computed.outcomeIsOverridden).toBe(true);
    expect(by("p8")?.outcomeOverrideNote).toBeTruthy();
  });
});
